version: "3"
services:
  app:
    image: app:latest
    container_name: app
    depends_on:
      - db
      - redis
      - rabbit
      - tarantool
    environment:
      - SERVER_PORT=8083
      - DB_POSTGRES_HOST=db
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_NAME=users
      - DB_POSTGRES_USERNAME=postgres
      - DB_POSTGRES_PASSWORD=slava
      - SCHEDULER_DELAY=6000
      - REDIS_URL=redis://redis:6379
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=admin
      - RABBIT_STOMP_PORT=61613
      - TARANTOOL_HOST=tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_USER=admin
      - TARANTOOL_PASSWORD=admin

  db:
    image: postgres:13.3
    container_name: db
    environment:
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=slava
    command: /bin/bash -c "until pg_isready -U postgres -p 5432; do sleep 1; done; psql -U postgres -c 'CREATE DATABASE users;'"

  redis:
    image: redis:latest
    container_name: redis

  rabbit:
    image: pcloud/rabbitmq-stomp:latest
    container_name: rabbit

  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool
    environment:
      - TARANTOOL_USER_NAME=admin
      - TARANTOOL_USER_PASSWORD=admin
    volumes:
      - ./tarantool/start.lua:/opt/tarantool/start.lua


