version: "3"
services:
  app:
    image: app:latest
    container_name: app
    depends_on:
      - db
      - redis
      - rabbit
    environment:
      - DB_POSTGRES_HOST=db
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_NAME=users
      - DB_POSTGRES_USERNAME=postgres
      - DB_POSTGRES_PASSWORD=slava
      - SCHEDULER_DELAY=6000
      - REDIS_URL=redis://redis:6379
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672

  db:
    image: postgres:13.3
    container_name: db
    environment:
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=slava
    command: /bin/bash -c "until pg_isready -U postgres -p 5432; do sleep 1; done; psql -U postgres -c 'CREATE DATABASE users;'"

  redis:
    image: redis:latest
    container_name: redis

  rabbit:
    image: rabbitmq:latest
    container_name: rabbit

