server:
  port: ${SERVER_PORT:8083}
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
  datasource:
    url: jdbc:postgresql://${DB_POSTGRES_HOST:localhost}:${DB_POSTGRES_PORT:5432}/${DB_POSTGRES_NAME:users}
    driver-class-name: org.postgresql.Driver
    username: ${DB_POSTGRES_USERNAME:postgres}
    password: ${DB_POSTGRES_PASSWORD:slava}
scheduler:
  fixedDelay: ${SCHEDULER_DELAY:6000}
app:
  jwtSecret: jZD5b4vFjQBADVTeCXvd5dR4nreA8uFH74FA9mNgM93tkH1chnElNlXsa4VRdxF
  jwtExpirationMs: 100000000
